title: Mohammed El Aouri ğŸ“
logo: /assets/img/profile-image.png
description: Full-stack web developer and a software engineering student. 
I'm excited to share my knowledge and collaborate with you all!
show_downloads: true
theme: jekyll-theme-minimal
