title: Mohammed El Aouri ğŸ“
logo: /assets/img/profile-image.png
description: Full-stack web developer and a software engineering student. 
show_downloads: true
theme: jekyll-remote-theme
remote_theme: pages-themes/architect@v0.2.0

